### ISSUE TITLE
idea: measure

### ISSUE THREAD

**Issue by chharvey** [chharvey/xmeter#13]
Measure is the inline length of a line of text.

opportunity to use logical properties and the `ch` unit!

```css
.h-Measure { max-inline-size: 66ch; }
```

http://tachyons.io/docs/typography/measure/

http://practicaltypography.com/line-length.html
