### ISSUE TITLE
logical properties

### ISSUE THREAD

**Issue by chharvey** [chharvey/xmeter#15]
## __tool.border-radius.less
(note that the `@radius` variable could take the form of one or two values, e.g. `@radius: 2px 4px` for the x- and y- radii, in that order)
```less
// could the following 4 mixins be css shorthand properties?
.border-block-start-radius(@radius: 0) {
  border-start-start-radius: @radius;
  border-start-end-radius:   @radius;
}
.border-block-end-radius(@radius: 0) {
  border-end-start-radius: @radius;
  border-end-end-radius:   @radius;
}
.border-inline-start-radius(@radius: 0) {
  border-start-start-radius: @radius;
  border-end-start-radius:   @radius;
}
.border-inline-end-radius(@radius: 0) {
  border-start-end-radius: @radius;
  border-end-end-radius:   @radius;
}
```
Related: https://github.com/w3c/csswg-drafts/issues/491

## __tool.borders.less
```less
.border-block(start; @width: 0) {
  border-block-start-width: @width;
  margin-block-start: (-@width);
}
.border-block(end; @width: 0) {
  border-block-end-width: @width;
  margin-block-start: (-@width);
}
.border-block(block; @width: 0) {
  border-block-width: @width;
  margin-block-start: (-2 * @width);
}
.border-block(all; @width: 0) {
  border-width: @width;
  margin-block-start: (-2 * @width);
}
```

## _c-Permalink.less
```less
.c-Permalink {
  margin-inline-start: 1rem;
}
```

## _h-Hidden.less
```less
.h-Hidden {
  inset-inline-start: -999999px;
}
```

## _h-Ruled.less
```less
.h-Ruled {
  background-position-block: end;
}
```
