### ISSUE TITLE
idea for Grid Object

### ISSUE THREAD

**Issue by chharvey** [chharvey/xmeter#18]
allow [custom properties to determine](https://css-tricks.com/css-attr-function-got-nothin-custom-properties/) the layout of `.o-Grid` object:
```css
.o-Grid {
  grid-template-rows   : repeat(var(--rows, 1), 1fr);
  grid-template-columns: repeat(var(--cols, 1), 1fr);
}
```
```html
<ul class="o-Grid" style="--rows: 2; --cols: 3;">
  <li class="o-Grid__Item">1</li>
  <li class="o-Grid__Item">2</li>
  <li class="o-Grid__Item">3</li>
  <li class="o-Grid__Item">4</li>
  <li class="o-Grid__Item">5</li>
  <li class="o-Grid__Item">6</li>
</ul>
```

[In the future](https://www.w3.org/TR/css-values-3/#attr-notation):
```css
.o-Grid {
  grid-template-rows   : repeat(attr(data-rows number, 1), 1fr);
  grid-template-columns: repeat(attr(data-cols number, 1), 1fr);
}
```
```html
<ul class="o-Grid" data-rows"2" data-cols="3">
  <li class="o-Grid__Item">1</li>
  <li class="o-Grid__Item">2</li>
  <li class="o-Grid__Item">3</li>
  <li class="o-Grid__Item">4</li>
  <li class="o-Grid__Item">5</li>
  <li class="o-Grid__Item">6</li>
</ul>
```
