### ISSUE TITLE
use detached rulesets / private variables

### ISSUE THREAD

**Issue by chharvey** [chharvey/xmeter#5]
http://lesscss.org/features/#detached-rulesets-feature-scoping

test this first, before implementing!

instead of
```less
#XMETER {
    .VARS() {
        @xmeter_line_height: 1.5;
    }
}
body {
    #XMETER .VARS();
    line-height: @xmeter_line_height;
}
```
try:
```less
@XMETER: { // detached ruleset
    @xmeter_line_height: 1.5;
};
body {
    @XMETER();
    line-height: @xmeter_line_height;
}
```

should also be used with mixins:
```less
@XMETER: {
    .box-sizing(@box) {
        -webkit-box-sizing: @box;
           -moz-box-sizing: @box;
                box-sizing: @box;
    }
};
*, *::before, *::after {
    @XMETER();
    .box-sizing(border-box);
}
```

close the issue if this does not work.
